version: '3'

networks:
  Inception:
    name: Inception

################ VOLUMES ################

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${USER}/data/wordpress
      o: bind
      type: none

################ SERVICES ################
services:
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
     - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - Inception
      
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
     - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - Inception
    depends_on:
      - mariadb
      
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    volumes:
     - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - Inception
    depends_on:
      - wordpress
